wandb:
  sweep:
    name: "Sweep"
    use: False
    yaml: "sweep.yaml"
  group:
    name: "cam"
  project:
    name: "BuilT"

dataset:
  name: "TweetDataset"
  params:
    max_len: 96
    model_path: "tweet/input/roberta-base/"
    csv_path: "tweet/input/tweet-sentiment-extraction/train.csv"

  splits:
    # - train: True
    #   csv_path: ''
    # - train: False
    #   csv_path: ''

splitter:
  name: "TweetSplitter"
  params:
    csv_path: "tweet/input/tweet-sentiment-extraction/train.csv"
    n_splits: 5
    shuffle: True
    random_state: 42


transforms:
  name: ""
  num_preprocessor: 1
  params:
    - ToTensor:
      name: "ToTensor"
    - Normalize:
      name: "Normalize"
      params:
        mean: !!python/tuple [0.1307]
        std: !!python/tuple [0.3081]

model:
  name: "TweetSentimentClassificationModel"
  params:
    transformer_type: "roberta"
    transformer_path: "tweet/input/roberta-base/"
    drop_out_rate: 0.1
    num_classes: 3

train:
  dir: "train_dirs/[TR_CORR]_[SC]_[ROB]/0_fold"
  name: ""
  batch_size: 256
  num_epochs: 1
  gradient_accumulation_step: 1

evaluation:
  batch_size: 8

loss:
  name: "TweetLoss"

optimizer:
  name: "AdamW"
  params:
    lr: 0.00003

scheduler:
  name: "MultiStepLR"
  params:
    milestones: [3, 4, 5]
    gamma: 0.1

forward_hook:
  name: "CAMForwardHook"
  # name: "TweetForwardHook"

post_forward_hook:
  name: "TweetPostForwardHook"

metric_hook:
  name: "TweetMetric"

logger_hook:
  name: "TweetLogger"
  params:
    use_tensorboard: True
    use_wandb: False
