wandb:
  sweep:
    name: "Sweep"
    use: False
    yaml: "sweep.yaml"
  group:
    name: "17.[TR_CORR]_[SE]_[En]_[ROB]"
  project:
    name: "built-mdpi-sensors"

dataset:
  name: "TweetDataset"
  params:
    max_len: 96
    model_path: "tweet/input/roberta-base/"
    csv_path: "tweet/input/tweet-sentiment-extraction/corrected_new_train.csv"

  splits:
    # - train: True
    #   csv_path: ''
    # - train: False
    #   csv_path: ''

splitter:
  name: "TweetSplitter"
  params:
    csv_path: "tweet/input/tweet-sentiment-extraction/corrected_new_train.csv"
    n_splits: 5
    shuffle: True
    random_state: 42


transforms:
  name: ""
  num_preprocessor: 1
  params:
    - ToTensor:
      name: "ToTensor"
    - Normalize:
      name: "Normalize"
      params:
        mean: !!python/tuple [0.1307]
        std: !!python/tuple [0.3081]

model:
  name: "TweetIndexExtractModel"
  params:
    transformer_type: "roberta"
    transformer_path: "tweet/input/roberta-base/"
    drop_out_rate: 0.3

train:
  dir: "train_dirs/[TR_CORR]_[SE]_[En]_[ROB]"
  name: ""
  batch_size: 32
  num_epochs: 5
  gradient_accumulation_step: 1

evaluation:
  batch_size: 8

loss:
  name: "SmoothLabelLoss"

optimizer:
  name: "AdamW"
  params:
    lr: 0.00003

scheduler:
  name: "MultiStepLR"
  params:
    milestones: [3, 4, 5]
    gamma: 0.1

forward_hook:
  name: "TweetIndexExtractionForwardHook"

post_forward_hook:
  name: "TweetPostForwardHook"

metric_hook:
  name: "TweetIndexExtractionMetric"

logger_hook:
  name: "TweetIndexExtractionLogger"
  params:
    use_tensorboard: False
    use_wandb: True
