language: python
python:
 - "3.7"
install:
 - pip install -r requirements.txt
 - pip install codecov
 - pip install coverage
script:
 - coverage run -m unittest discover tests
after_success:
 - bash <(curl -s https://codecov.io/bash)