dataset:
  name: "DefaultDataset"
  params:
    idx_fold: 0
    data_dir: "data"

  splits:
    - mode: "train"
      split: "train"
    - mode: "validation"
      split: "test"
    - mode: "validation"
      split: "val"

transform:
  name: "DefaultTransform"
  num_preprocessor: 8
  params:
    resize_to: (224, 224)

model:
  name: "DefaultModel"
  params:
    num_classes: 3

train:
  dir: "train_dirs/default"
  batch_size: 8
  gradient_accumulation_step: 1
  num_epochs: 3
  no_bias_decay: True
  encoder_lr_ratio: 0.1

evaluation:
  batch_size: 8

loss:
  name: "BCEWithLogitsLoss"

optimizer:
  name: "AdamW"
  params:
    lr: 0.00025
    weight_decay: 0.01

scheduler:
  name: "MultiStepLR"
  params:
    milestones: !!python/tuple [1, 3, 5]
    gamma: 0.1

hooks:
  metric:
    name: "DefaultMetricHook"

  post_forward:
    name: "DefaultPostForwardHook"

  write_result:
    name: "DefaultWriteResultHook"
