program: train.py
method: grid
metric:
  goal: minimize
  name: loss
parameters:
  batch_size:
    values: [1, 32, 64]
  learning_rate:
    values: [0.001, 0.005, 0.0005]
  epochs:
    value: [10, 50, 100]
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27